### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by philn** [comment]
What are you up to @ferjm ? :) I can merge this PR in my repo if you want.

**Comment by sdroege** [comment]
Would be better to merge it in @philn 's repository, that's the "canonical" location :) Thanks for the changes btw!

**Comment by philn** [comment]
I actually have a few more changes in the "upstream" repo :P Perhaps you'd like to check them out.

**Comment by ferjm** [comment]
I was just trying to update and test https://github.com/sdroege/servo/tree/gst We may end up using GStreamer in Servo soon :)

I didn't realize that this was a fork of @philn's repo. Thanks for the pointer! :)

**Comment by philn** [comment]
Hah, nice!! I rebased my Servo gst branch some time ago, https://github.com/philn/servo/tree/gst Maybe have a look at it, I doubt the htmlmediaelement.rs code changed a lot since end of January.

**Comment by sdroege** [comment]
> We may end up using GStreamer in Servo soon :)

@ferjm That sounds great! Any public information about that, plans, etc? If there are any questions about GStreamer, be it usage from Rust, web-related things or just in general, feel free to ask :)

**Comment by ferjm** [comment]
> Hah, nice!! I rebased my Servo gst branch some time ago, https://github.com/philn/servo/tree/gst Maybe have a look at it, I doubt the htmlmediaelement.rs code changed a lot since end of January.

Hah! I should check github more often :D I rebased @sdroege's branch again https://github.com/sdroege/servo/pull/1 I'll close that PR and use your branch instead :)

> @ferjm That sounds great! Any public information about that, plans, etc? If there are any questions about GStreamer, be it usage from Rust, web-related things or just in general, feel free to ask :)

No public information or real plans yet. So far it's just me checking your previous work and trying to learn about GStreamer :). I'll let you know if this ends up being an official goal for the team. Thank you!

**Pull request closed without merging**
